# Generated by Django 2.0.2 on 2021-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100, null=True)),
                ('productPrice', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
